services:

    db:
      restart: 'always'
      image: mariadb:10.5
      command: 'mysqld --character-set-server=utf8 --collation-server=utf8_general_ci'
      working_dir: /code
      env_file:
        - local.env
      environment:
        MYSQL_DATABASE: drugref2
        MYSQL_USER: oscar
        TZ: America/Vancouver
      volumes:
        # TODO: build this in to the image.
        - ./docker/db/my.cnf:/etc/mysql/my.cnf
        # TODO: build some scripts in so we need not mount everything.
        - .:/code
        - mariadb-files:/var/lib/mysql
      networks:
        - back-tier
      deploy:
        resources:
          limits:
            cpus: '2'
            memory: 15G

    oscar:
      restart: 'always'
      image: openosp/open-osp:latest
      build: docker/oscar
      volumes:
        - ./volumes/oscar.properties:/root/oscar.properties
        - ./volumes/drugref2.properties:/root/drugref2.properties
        - ./volumes/OscarDocument:/var/lib/OscarDocument
        - ./volumes/ssl.crt:/usr/local/tomcat/conf/ssl.crt
        - ./volumes/ssl.key:/usr/local/tomcat/conf/ssl.key
        - ./volumes/chain.pem:/usr/local/tomcat/conf/chain.pem
        # Add other volumes to the volumes/ folder, and mount them via docker-compose.override.yml
      networks:
        - back-tier
      environment:
        TZ: America/Vancouver
        CATALINA_OPTS: -Djava.awt.headless=true
        JAVA_OPTS: -Dlog4j2.formatMsgNoLookups=true -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseConcMarkSweepGC -Xmx2G -Xms2G -XX:MaxPermSize=1G -XX:CMSInitiatingOccupancyFraction=68 -Xincgc -Dorg.apache.el.parser.COERCE_TO_ZERO=true
      deploy:
        resources:
          limits:
            cpus: '2'
            memory: 15G

    expedius:
      restart: 'always'
      image: openosp/expedius:latest
      build: docker/expedius
      volumes:
        - ./volumes/ssl.crt:/usr/local/tomcat/conf/ssl.crt
        - ./volumes/ssl.key:/usr/local/tomcat/conf/ssl.key
        - ./volumes/expedius:/var/lib/expedius
        - ./volumes/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      networks:
        - back-tier
      environment:
        TZ: America/Vancouver
        JAVA_OPTS: -Dlog4j2.formatMsgNoLookups=true
      deploy:
        resources:
          limits:
            cpus: '2'
            memory: 4G

    faxws:
      restart: 'always'
      image: openosp/faxws:latest
      build: docker/faxws
      volumes:
        - ./volumes/OscarDocument:/var/lib/OscarDocument
        - ./volumes/ssl.crt:/usr/local/tomcat/conf/ssl.crt
        - ./volumes/ssl.key:/usr/local/tomcat/conf/ssl.key
      networks:
        - back-tier
      env_file:
        - local.env
      environment:
        TZ: America/Vancouver
        MYSQL_HOST: db
        JAVA_OPTS: -Dlog4j2.formatMsgNoLookups=true
      deploy:
        resources:
          limits:
            cpus: '2'
            memory: 4G

volumes:
  mariadb-files:
    driver: local

networks:
  back-tier:
    driver: bridge
