services:

    builder:
      image: openosp/builder
      build: docker/builder
      volumes:
        - .:/code
        - $HOME/.m2:/root/.m2
      working_dir: /code
      command: ./build-release.sh
      environment:
        - OSCAR_TREEISH
        - OSCAR_REPO
        - JOB_NAME
        - BUILD_NUMBER
      networks:
        - back-tier
      
networks:
  back-tier:
    driver: bridge

